### ISSUE TITLE
Counter is not displayed correctly in the overview

### ISSUE THREAD

**Issue by e-i-k-e** [stormmurdoc/victron_sdm630_bridge#2]
Hello,

the overview is not displayed correctly for me.
The Counter recognized and the MP2 regulates accordingly.

How do I get the counter from "AC loads" to the grid counter?
There is no load on outputs 1 and 2 on the MP2.

I'm not ruling out a bad configuration on my part. ;)

![image](https://user-images.githubusercontent.com/83473829/160237034-000c7ef2-45d1-4350-b786-9f4f1efe3296.png)

![image](https://user-images.githubusercontent.com/83473829/160237046-97e32126-18ff-42ba-8a66-0fed05969dab.png)
![image](https://user-images.githubusercontent.com/83473829/160237053-7c0fe9bb-a59c-4a6f-b3a8-1eefade756a9.png)
![image](https://user-images.githubusercontent.com/83473829/160237064-2fee2cf7-a7b6-430d-910d-c1aa0e3a8592.png)
![image](https://user-images.githubusercontent.com/83473829/160237069-4b9372c7-9bf7-4931-bc8f-25415fd16b67.png)

**Comment by stormmurdoc** [comment]
On which phase did you connect the MP? Did you not activate the ESS?

**Comment by e-i-k-e** [comment]
> On which phase did you connect the MP? Did you not activate the ESS?

The MP2 runs on L1.  Ess is activated.

**Comment by stormmurdoc** [comment]
In my point of view this is an issue of an misconfigured ESS system. Please doublecheck again.
