### ISSUE TITLE
On MQTT disconnection, meter does not reconnect again.

### ISSUE THREAD

**Issue by e-i-k-e** [stormmurdoc/victron_sdm630_bridge#4]
Hello,
I have found that as soon as the MQTT connection is briefly interrupted, the meter does not reconnect independently.
The value of the counter remains at the last value.
Only a restart of VenusOS helps.

**Comment by e-i-k-e** [comment]
@stormmurdoc 
I would be very grateful if you could help me with this problem.

**Comment by hleber** [comment]
I have solved that by a script:
run.sh
----- begin of file ----
#!/bin/sh
```
while true; do
  /data/sdm630/sdm630-bridge
  sleep 1
done
```
----  end of file ----

and a change in the connectLostHandler

--- code change ---
```
var connectLostHandler mqtt.ConnectionLostHandler = func(client mqtt.Client, err
    log.Info(fmt.Sprintf("Connect lost: %v", err))
    os.Exit(1) /* THIS IS NEW */
}
```
--- end code change ---

When ever a connection ist lost, the service is starting again

**Comment by stormmurdoc** [comment]
Hi @hleber, thanks for your workaround. I've updated the source code and released version 0.2

**Comment by stormmurdoc** [comment]
@e-i-k-e Please try out the new workaround!

**Comment by e-i-k-e** [comment]
> @e-i-k-e Please try out the new workaround!

Hello,
it works.

Thank you! :)

**Comment by stormmurdoc** [comment]
Perfect! Thanks for the feedback.
