### ISSUE TITLE
Provide this bridge by a Package Manager

### ISSUE THREAD

**Issue by leowinterde** [stormmurdoc/victron_sdm630_bridge#8]
Just a long-term feature idea: Add support for the VenusOS package manager from https://github.com/kwindrem/SetupHelper. This would provide automatic reinstallation and updates after every VenusOS upgrade.

**Comment by stormmurdoc** [comment]
Sounds good - I'll check it out.

**Comment by blackpearlla** [comment]
Hi @stormmurdoc, did you have any news about the package manager?

**Comment by stormmurdoc** [comment]
Hi @blackpearlla , sorry but I'm too busy. PRs are welcome ;-)
